[tool.poetry]
name = "triangles"
version = "0.1.0"
description = ""
authors = ["9996698 <ise.gura@bsu.by>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
